const meals = [
    {
        "meal_name": 'Asian-Style Chicken Orzo Salad',
        "img_url": 'https://lfuen.github.io/laCarte/images/meals/orzo.jpg',
        "ingredients": ['Edamame',
        'Orzo',
        'Chicken',
        'Onions',
        'Pepper',
        'Vegetable Oil',
        'Sesame Oil',
        'Ginger',
        'Rice Wine Vinegar',
        'Soy Sauce',
        'Hoisin Sauce',
        'Almonds'],
        "chef":['Johnathan', 'Francesca', 'Christian', 'Madelyn'],
        "origin": 'Asian',
    },
    {
        "meal_name": 'Bibimbap',
        "img_url": 'https://lfuen.github.io/laCarte/images/meals/bibimbap.jpg',
        "ingredients": ['Garlic',
        'Ginger',
        'Fish Sauce',
        'Gochujang Chili Paste',
        'Sugar',
        'Rice Wine Vinegar',
        'Sesame',
        'Cabbage',
        'Cucumber',
        'Bean Sprouts',
        'Soy Sauce',
        'Sirloin',
        'Sesame Oil',       
        'Carrot',
        'Spinach',
        'Sunflower Oil',
        'Eggs'],
        "chef":['Johnathan', 'Francesca', 'Christian', 'Madelyn'],
        "origin": 'Asian',
    },
    {
        "meal_name": 'Butter Chicken With Spinach',
        "img_url": 'https://lfuen.github.io/laCarte/images/meals/butterChicken.jpg',
        "ingredients": ['Spinach',
        'Garlic',
        'Yogurt',
        'Almonds',
        'Garams Masala',
        'Five-Spice Indian Powder',
        'Cinnamon',
        'Cardamom',
        'Ginger',
        'Tomatoes',
        'Salt',
        'Chicken',
        'Clarified Butter',
        'Onions',
        'Coconut Milk',
        'Vegetable Stock'],
        "chef":['Johnathan', 'Christian', 'Madelyn'],
        "origin": 'Indian',
    },
    {
        "meal_name": 'Baba Ghanoush',
        "img_url": 'https://lfuen.github.io/laCarte/images/meals/baba.jpg',
        "ingredients": ['Eggplant',
        'Flaxseed Oil',
        'Garlic',
        'Lemon Juice',
        'Cumin',
        'Tahini',
        'Extra-Virgin Olive Oil',
        'Pine Nuts',
        'Parsley',
        'Paprika',
        'Salt',
        'Black Pepper'],
        "chef":['Johnathan', 'Joaquin', 'Christian'],
        "origin": 'Middle Eastern',
    }

];

export default meals